version: '3.8'

# 适用于新环境的一键部署方案
# 自动创建MySQL、Redis服务和Claude Code Relay应用

services:
  mysql:
    image: mysql:8.0
    container_name: claude-code-relay-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-jie1306105459}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-claude_code_relay}
      MYSQL_USER: ${MYSQL_USER:-claude}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-jie1306105459}
      # 时区设置
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      # MySQL配置文件（可选）
      # - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+08:00'
      --innodb-buffer-pool-size=256M
      --max-connections=1000
    networks:
      - claude-network
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    # 安全配置
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7.0-alpine
    container_name: claude-code-relay-redis
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - redis_data:/data
      # Redis配置文件（可选）
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1 300 10 60 10000
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 3
      start_period: 10s
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    # 安全配置
    security_opt:
      - no-new-privileges:true

  app:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/claude-code-relay:latest
    container_name: claude-code-relay-app
    restart: unless-stopped
    ports:
      - "10081:8080"
    env_file:
      - .env
    environment:
      # 时区配置
      TZ: Asia/Shanghai
      
      # MySQL数据库连接配置
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER:-claude}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-claude123456}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-claude_code_relay}
      
      # Redis连接配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      
      # 生产环境配置
      GIN_MODE: ${GIN_MODE:-release}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - app_logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - claude-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    # 安全配置
    security_opt:
      - no-new-privileges:true

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/redis
  app_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

networks:
  claude-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1